meta_product_name: "LairBnb"
meta_title: "LairBnb - Find Your Next Lair"
meta_description: "The sharing economy comes to the comic book universe! Find the perfect superhero or villain lair for your travels."
meta_image: "withname.png"
twitter_account: "@lairbnb"   